
DROP TABLE MYBOARD;
DROP SEQUENCE MYNOSEQ;

CREATE SEQUENCE MYNOSEQ;


CREATE TABLE MYBOARD(
MYNO NUMBER PRIMARY KEY,
MYNAME VARCHAR2(1000) NOT NULL,
MYTITLE VARCHAR2(1000) NOT NULL,
MYCONTENT VARCHAR2(1000) NOT NULL,
MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL,'정은주','잘하자','좀 나아져라~',SYSDATE);

SELECT * FROM MYBOARD;
